# frozen_string_literal: true

require "tmpdir"
require "fileutils"
require "stringio"
require "guardrails/init"

RSpec.describe Guardrails::Init do
  let(:root) { Pathname(Dir.mktmpdir) }
  after { FileUtils.rm_rf(root) }

  it "runs detection and prints a summary" do
    output = StringIO.new
    described_class.new(root: root, output: output).run

    expect(output.string).to include("Guardrails — stack detection")
    expect(output.string).to include("Strategy: No stylesheets found (none)")
  end

  it "returns the detection result" do
    result = described_class.new(root: root, output: StringIO.new).run

    expect(result.strategy).to eq(:none)
  end

  it "writes guardrails.yml as part of the run" do
    described_class.new(root: root, output: StringIO.new).run

    expect(root.join("guardrails.yml")).to exist
  end

  it "skips media-query scaffolding when guardrails.yml already exists" do
    root.join("guardrails.yml").write("# pre-existing")
    root.join("app/assets/stylesheets/tokens").mkpath
    token_file = root.join("app/assets/stylesheets/tokens/_colors.scss")
    token_file.write("$primary: #0066ff;\n")

    output = StringIO.new
    described_class.new(root: root, output: output).run

    expect(output.string).to include("refusing to overwrite")
    expect(output.string).to include("Media queries: skipped")
    expect(token_file.read(encoding: Encoding::UTF_8)).not_to include("prefers-color-scheme")
  end

  it "uses prompted near_match_policy when stdin is a TTY" do
    tty = StringIO.new("fix\n\n\n") # near_match_policy choice + accept defaults for paths/ignore
    allow(tty).to receive(:tty?).and_return(true)

    described_class.new(root: root, output: StringIO.new, input: tty).run

    written = YAML.safe_load_file(root.join("guardrails.yml"))
    expect(written["guardrails"]["tokens"]["near_match_policy"]).to eq("fix")
  end

  it "uses defaults when stdin is not a TTY" do
    non_tty = StringIO.new
    allow(non_tty).to receive(:tty?).and_return(false)

    described_class.new(root: root, output: StringIO.new, input: non_tty).run

    written = YAML.safe_load_file(root.join("guardrails.yml"))
    expect(written["guardrails"]["tokens"]["near_match_policy"]).to eq("notify")
    expect(written["guardrails"]["audit"]["scan_paths"]).to eq(%w[app/views app/components])
  end

  it "honors prompted overrides for scan_paths and ignore" do
    tty = StringIO.new("\nlib/templates,app/views\nconfig\n") # default policy, custom paths
    allow(tty).to receive(:tty?).and_return(true)

    described_class.new(root: root, output: StringIO.new, input: tty).run

    written = YAML.safe_load_file(root.join("guardrails.yml"))
    expect(written["guardrails"]["audit"]["scan_paths"]).to eq(%w[lib/templates app/views])
    expect(written["guardrails"]["audit"]["ignore"]).to eq(%w[config])
  end

  it "overwrites an existing guardrails.yml when force is true" do
    root.join("guardrails.yml").write("# stale config")
    root.join("app/assets/stylesheets/tokens").mkpath
    token_file = root.join("app/assets/stylesheets/tokens/_colors.scss")
    token_file.write("$primary: #0066ff;\n")

    described_class.new(root: root, output: StringIO.new, force: true).run

    expect(root.join("guardrails.yml").read(encoding: Encoding::UTF_8)).to include("Generated by `rails guardrails:init`")
    # MQ scaffolder runs after a forced write
    expect(token_file.read(encoding: Encoding::UTF_8)).to include("prefers-color-scheme")
  end

  it "does not prompt when guardrails.yml exists and force is false" do
    root.join("guardrails.yml").write("# pre-existing")
    tty = StringIO.new("fix\nhellbroken,paths\nweird\n")
    allow(tty).to receive(:tty?).and_return(true)
    output = StringIO.new

    described_class.new(root: root, output: output, input: tty).run

    # The prompter writes the question text to output; if any prompt fired,
    # we'd see it. Confirm no prompt traces leaked.
    expect(output.string).not_to include("Near-match auto-fix policy:")
    expect(output.string).not_to include("Audit scan paths")
    expect(output.string).to include("refusing to overwrite")
  end
end
