# frozen_string_literal: true

require "tmpdir"
require "fileutils"
require "stringio"
require "yaml"
require "guardrails/init/stack_detector"
require "guardrails/init/config_writer"

RSpec.describe Guardrails::Init::ConfigWriter do
  let(:root) { Pathname(Dir.mktmpdir) }
  after { FileUtils.rm_rf(root) }

  def detection_result(strategy:, evidence_overrides: {})
    Guardrails::Init::StackDetector::Result.new(
      strategy: strategy,
      stylesheets: [],
      evidence: { files_scanned: 0, custom_property_files: 0, scss_variable_files: 0, raw_hex_files: 0 }
        .merge(evidence_overrides)
    )
  end

  def written_config
    YAML.safe_load_file(root.join("guardrails.yml"))
  end

  describe "#write" do
    it "writes guardrails.yml with the detected strategy" do
      result = detection_result(strategy: :css_custom_properties)
      described_class.new(root, output: StringIO.new).write(result)

      expect(root.join("guardrails.yml")).to exist
      expect(written_config["guardrails"]["tokens"]["strategy"]).to eq("css_custom_properties")
    end

    it "uses .css token paths for css_custom_properties" do
      result = detection_result(strategy: :css_custom_properties)
      described_class.new(root, output: StringIO.new).write(result)

      tokens = written_config["guardrails"]["tokens"]
      expect(tokens["colors_file"]).to eq("app/assets/stylesheets/tokens/_colors.css")
      expect(tokens["type_scale_file"]).to eq("app/assets/stylesheets/tokens/_type.css")
    end

    it "uses .scss token paths for scss_variables" do
      result = detection_result(strategy: :scss_variables)
      described_class.new(root, output: StringIO.new).write(result)

      tokens = written_config["guardrails"]["tokens"]
      expect(tokens["colors_file"]).to eq("app/assets/stylesheets/tokens/_colors.scss")
      expect(tokens["type_scale_file"]).to eq("app/assets/stylesheets/tokens/_type.scss")
    end

    it "leaves token paths nil when no token system was detected" do
      result = detection_result(strategy: :raw_hex)
      described_class.new(root, output: StringIO.new).write(result)

      tokens = written_config["guardrails"]["tokens"]
      expect(tokens["colors_file"]).to be_nil
      expect(tokens["type_scale_file"]).to be_nil
    end

    it "defaults near_match_policy to notify" do
      result = detection_result(strategy: :scss_variables)
      described_class.new(root, output: StringIO.new).write(result)

      expect(written_config["guardrails"]["tokens"]["near_match_policy"]).to eq("notify")
    end

    it "writes a header comment with the detected strategy" do
      result = detection_result(strategy: :scss_variables)
      described_class.new(root, output: StringIO.new).write(result)

      content = root.join("guardrails.yml").read
      expect(content).to start_with("# Generated by `rails guardrails:init`")
      expect(content).to include("Detected stylesheet strategy: scss_variables")
    end

    it "warns about unset token paths when strategy is raw_hex" do
      result = detection_result(strategy: :raw_hex)
      described_class.new(root, output: StringIO.new).write(result)

      content = root.join("guardrails.yml").read
      expect(content).to include("No token system detected")
    end

    it "refuses to overwrite an existing guardrails.yml" do
      root.join("guardrails.yml").write("existing content")
      output = StringIO.new

      written = described_class.new(root, output: output).write(detection_result(strategy: :scss_variables))

      expect(written).to be(false)
      expect(root.join("guardrails.yml").read).to eq("existing content")
      expect(output.string).to include("refusing to overwrite")
    end

    it "returns true on successful write" do
      written = described_class.new(root, output: StringIO.new).write(detection_result(strategy: :none))
      expect(written).to be(true)
    end

    it "honors overrides for near_match_policy, scan_paths, and ignore" do
      result = detection_result(strategy: :scss_variables)
      overrides = {
        near_match_policy: "fix",
        scan_paths: ["lib/templates"],
        ignore: ["lib/templates/legacy"]
      }
      described_class.new(root, output: StringIO.new).write(result, overrides: overrides)

      config = written_config
      expect(config["guardrails"]["tokens"]["near_match_policy"]).to eq("fix")
      expect(config["guardrails"]["audit"]["scan_paths"]).to eq(["lib/templates"])
      expect(config["guardrails"]["audit"]["ignore"]).to eq(["lib/templates/legacy"])
    end

    it "overwrites an existing config when force is true" do
      root.join("guardrails.yml").write("# stale")
      output = StringIO.new

      written = described_class.new(root, output: output).write(detection_result(strategy: :scss_variables), force: true)

      expect(written).to be(true)
      expect(output.string).to include("Overwrote guardrails.yml")
      expect(root.join("guardrails.yml").read).to include("Generated by `rails guardrails:init`")
    end

    it "tells the user about FORCE=1 when refusing to overwrite" do
      root.join("guardrails.yml").write("existing")
      output = StringIO.new

      described_class.new(root, output: output).write(detection_result(strategy: :scss_variables))

      expect(output.string).to include("FORCE=1")
    end
  end
end
