# frozen_string_literal: true

require "pathname"
require "yaml"

module Guardrails
  class Init
    class ConfigWriter
      CONFIG_FILENAME = "guardrails.yml"

      DEFAULT_TOKEN_PATHS = {
        css_custom_properties: {
          "colors_file" => "app/assets/stylesheets/tokens/_colors.css",
          "type_scale_file" => "app/assets/stylesheets/tokens/_type.css"
        },
        scss_variables: {
          "colors_file" => "app/assets/stylesheets/tokens/_colors.scss",
          "type_scale_file" => "app/assets/stylesheets/tokens/_type.scss"
        },
        raw_hex: {
          "colors_file" => nil,
          "type_scale_file" => nil
        },
        none: {
          "colors_file" => nil,
          "type_scale_file" => nil
        }
      }.freeze

      def initialize(root, output: $stdout, now: Time.now)
        @root = Pathname(root)
        @output = output
        @now = now
      end

      def write(detection_result, overrides: {}, force: false)
        path = @root.join(CONFIG_FILENAME)
        existed = path.exist?
        if existed && !force
          @output.puts "#{CONFIG_FILENAME} already exists — refusing to overwrite."
          @output.puts "Delete or rename it, or set FORCE=1 to re-run init."
          return false
        end

        path.write(yaml_for(detection_result, overrides))
        @output.puts(existed ? "Overwrote #{CONFIG_FILENAME}" : "Wrote #{CONFIG_FILENAME}")
        true
      end

      private

      def yaml_for(result, overrides)
        token_paths = DEFAULT_TOKEN_PATHS.fetch(result.strategy)
        config = {
          "guardrails" => {
            "audit" => {
              "scan_paths" => overrides.fetch(:scan_paths, ["app/views", "app/components"]),
              "ignore" => overrides.fetch(:ignore, ["app/views/layouts"])
            },
            "icons" => {
              "source" => "app/assets/images/icons",
              "sprite_output" => "app/assets/images/icons/sprite.svg"
            },
            "tokens" => {
              "strategy" => result.strategy.to_s,
              "colors_file" => token_paths["colors_file"],
              "type_scale_file" => token_paths["type_scale_file"],
              "near_match_policy" => overrides.fetch(:near_match_policy, "notify")
            }
          }
        }

        header(result) + config.to_yaml(line_width: -1)
      end

      def header(result)
        unset_paths = result.strategy == :raw_hex || result.strategy == :none
        comment = +"# Generated by `rails guardrails:init` on #{@now.strftime('%Y-%m-%d')}\n"
        comment << "# Detected stylesheet strategy: #{result.strategy}\n"
        if unset_paths
          comment << "# No token system detected — colors_file and type_scale_file are unset.\n"
          comment << "# Create a token file and update tokens.colors_file before running guardrails:tokens.\n"
        end
        comment << "\n"
      end
    end
  end
end
